# Generated by Django 3.0.3 on 2020-03-03 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_details', models.CharField(max_length=2000)),
                ('question_answer', models.CharField(max_length=2000)),
                ('question_tags', models.CharField(max_length=3000)),
                ('time_questions_used', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('times_used', models.IntegerField()),
                ('tag_name', models.CharField(max_length=25)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_year', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('students_taken', models.IntegerField()),
                ('grade_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lowest_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('highest_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grades', models.IntegerField()),
                ('test_date', models.DateField()),
                ('test_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=40)),
                ('user_last_name', models.CharField(max_length=40)),
                ('user_password', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='tags',
            name='tests_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Tests'),
        ),
        migrations.AddField(
            model_name='tags',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.User'),
        ),
        migrations.AddField(
            model_name='questions',
            name='tests_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Tests'),
        ),
    ]
