# Generated by Django 3.0.3 on 2020-03-22 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200303_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='tests_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Tests'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Questions'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tests_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Tests'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.User'),
        ),
    ]
